@startuml SinooUC

skinparam shadowing false
left to right direction

actor "Khách Hàng" as KH
actor "Quản Lý/Chủ" as NVQL
actor "Nhân Viên Bán Hàng" as NVBH

rectangle "Hệ thống quản lý bán hàng và kho vật liệu xây dựng Thiên Ân" {

'>>>>>>>>>>>>>>> Khai báo >>>>>>>>>>>>>>>
'Danh mục sp
Usecase QLDMSP as "Quản lý danh mục"
note bottom of QLDMSP: Thêm/Sửa/Xóa danh mục
(Xem danh mục) as XEM_DMSP
(Tìm danh mục) as TIM_DMSP
 TIM_DMSP <.. XEM_DMSP: extend

'Kho hàng
Usecase QLKHO as "Quản lý phiếu nhập/xuất kho"
note bottom of QLKHO : Xem, tìm kiếm, tạo, cập nhật,  \nhủy phiếu nhập kho và phiếu xuất kho,  \nxem và cập nhật số lượng tồn kho 
(Xem số lượng tồn kho) as XEM_HANG
(Xem phiếu xuất kho) as XEM_PXK
(Tìm phiếu xuất kho) as TIM_PXK
TIM_PXK <. XEM_PXK: extend

'Nhân viên
Usecase QLNV as "Quản lý nhân viên"
note bottom of QLNV: Thêm/Sửa/Xóa/Xem/Tìm nhân viên

'Nhà cung cấp
Usecase QLNCC as "Quản lý nhà cung cấp"
note bottom of QLNCC: Thêm/Sửa/Xóa/Xem/Tìm nhà cung cấp
' (Tìm nhà cung cấp) as TIM_NCC

'Báo cáo
(Quản lý báo cáo) as QLBC
note bottom of QLBC: Xem doanh thu, phí nhập, phí xuất hàng

'Khách hàng
(Quản lý khách hàng) as QLKH
note top of QLKH: Thêm/Sửa/Xem/Tìm khách hàng

'Đơn hàng
Usecase QLDH as "Quản lý đơn hàng"
note top of QLDH: Xem, tìm kiếm, thêm, sửa và hủy đơn hàng,  \nxác nhận, theo dõi và cập nhật trạng thái đơn hàng.
' (Tìm đơn) as TIM_DH
' (Xem đơn) as XEM_DH

'Sản phẩm
Usecase QLSP as "Quản lý sản phẩm"
note top of QLSP: Thêm/Sửa/Xóa sản phẩm
(Xem sản phẩm) as XEM_SP
(Tìm sản phẩm) as TIM_SP
 TIM_SP <. XEM_SP: extend

'Giỏ hàng
Usecase QLGH as "Quản lý giỏ hàng"
note bottom of QLGH: Xem, thêm, cập nhật số lượng hoặc xóa sản phẩm khỏi giỏ hàng,  \nđặt hàng, xem lịch sử mua hàng,  theo dõi đơn hàng, yêu cầu hủy đơn hàng,  \nxác nhận hoặc cập nhật thông tin liên hệ và địa chỉ giao hàng.
' (Xem giỏ hàng) as XEM_GH
'   XEM_GH .>  QLGH: extend


'Đăng nhập, đăng xuất
(Đăng xuất) as Logout
(Đăng nhập) as Login
(Đăng kí) as SignUp
(Đổi mật khẩu) as ChangePass

Login  <.  Logout: include
ChangePass .> Login : extend

'>>>>>>>>>>>>>>> Gán đối tượng >>>>>>>>>>>>>>
QLDMSP ...> Login : include
QLBC ...> Login : include
QLDH ...> Login : include
QLGH ...> Login : include
QLSP ...> Login : include
QLNCC ...> Login : include
QLKH ...> Login : include
QLNV ...> Login : include
QLKHO ...> Login : include

'----------- Nhân Viên Quản lý -----------
NVQL --> QLSP
NVQL ----> QLDMSP
NVQL --> QLKHO
NVQL --> QLNV
NVQL --> QLNCC
NVQL --> QLBC
NVQL --> QLKH 
NVQL --> QLDH 

'Tài khoản
' NVQL ---> Login

'Sản phẩm
QLSP <... TIM_SP: extend

'Danh mục sp
QLDMSP <..... TIM_DMSP: extend

'Kho hàng
QLKHO <... XEM_HANG: extend
QLKHO <... TIM_PXK: extend

'Nhân viên

'Nhà cung cấp
' QLNCC <.. TIM_NCC: extend

'Báo cáo

'Khách hàng

'Đơn hàng


'----------- Nhân Viên Bán Hàng -----------
QLDH <- NVBH
QLKH <-- NVBH

'Tài khoản
' Login <--- NVBH

'Kho
XEM_HANG <--- NVBH

'Danh mục
TIM_DMSP <---- NVBH

'Kho hàng
TIM_PXK <--- NVBH

'Sản phẩm
TIM_SP <-- NVBH

'----------- Khách Hàng -----------
QLGH <--- KH

'Tài khoản
SignUp <- KH
' Login <-- KH

'Giỏ hàng
' XEM_GH <-- KH

'Sản phẩm
TIM_SP <---- KH

'Danh mục
TIM_DMSP <--- KH

}

@enduml
