@startuml SequenceAddNewProduct
actor User as user
boundary "UI: Quản lý sản phẩm" as ui_manageProduct
boundary "UI: Thêm sản phẩm" as ui_addProduct
control "Ctrl: Thêm sản phẩm" as ctrl_addProduct
database database

activate user
user -> ui_manageProduct: Chọn "Thêm sản phẩm"

activate ui_manageProduct
ui_manageProduct -> ui_addProduct: Yêu cầu hiển thị
deactivate ui_manageProduct

activate ui_addProduct
ui_addProduct --> user: Hiển thị form nhập sản phẩm
user -> ui_addProduct: Nhập thông tin sản phẩm
note right of user
Thông tin sản phẩm:tên sản phẩm, giá, 
đơn vị tính, chất liệu, kích thước, 
tiêu chuẩn, màu sắc, kiểu loại, thương hiệu, 
bảo hành, mô tả, hình ảnh
end note
ui_addProduct -> ctrl_addProduct: Thông tin sản phẩm và nhấn "Lưu"
deactivate ui_addProduct
activate ctrl_addProduct


ctrl_addProduct -> ctrl_addProduct: Kiểm tra hợp lệ và tồn tại

alt#Gold #Pink Lỗi không hợp lệ và tồn tại
    ctrl_addProduct -> ui_addProduct: Thông báo lỗi
    deactivate ctrl_addProduct
activate ui_addProduct
    ui_addProduct -> user: Thông báo lỗi
deactivate ui_addProduct
else #LightBlue Thông tin đã hợp lệ
    
    ctrl_addProduct -> database : Thông tin sản phẩm
activate ctrl_addProduct
activate database
    database --> ctrl_addProduct: Thông báo thành công
deactivate database

    ctrl_addProduct --> ui_addProduct: Thông báo thành công
deactivate ctrl_addProduct
activate ui_addProduct
    ui_addProduct --> user: Thông báo thành công
deactivate ui_addProduct
end
deactivate user
@enduml
