@startuml Class

top to bottom direction
skinparam {
    shadowing false
    backgroundColor #FFFFFF/#FEFEFE
    class {
        BackgroundColor #F5F5F7/#C1CFA1
        ArrowColor #A5B68D
        BorderColor #EDE8DC
        FontName "Montserrat"
        FontSize 18
        FontColor #333333
        StereotypeFontColor #666666
        StereotypeFontSize 15
        StereotypeFontName "Montserrat"
        roundCorner 10
    }
}

' --------------- ACTOR ---------------
class User {
    + id: String
    + fullName: String
    + phoneNumber: String
    + address: String
    + gender: String
    + dateOfBirth: String
    + password: String

    + changePassword(): void
    + forgotPassword(): void
    + updateProfile(): void
}

class Manager {
    + citizenId: String
    + issuingDate: Date
    + issuingPlace: String

    + changeInfo(): void
}

class SaleStaff {
    + citizenId: String
    + issuingDate: Date
    + issuingPlace: String

    + assistCustomerOrder(): void
}

class Customer {
    + changeInfo(): void
    + viewOrderHistory(): void
}

' --------------- UC ---------------

class Product {
    + id: Int
    + name: String
    + price: Double
    + unit: String
    + material: String
    + dimension: String
    + standard: String
    + color: String
    + brand: String
    + warrantyPeriod: String
    + description: String
    + mainImg: String
    + images: List<String>
    + CreatedDate: Date
    + isActive: Boolean
    + isImport: Boolean
}

'--- Export ---
' Define cart-related classes

' class Cart {
'     + id: Int
'     + totalPrice: Double
'     + totalQuantity: Int

'     + addItem(): void
'     + removeItem(): void
'     + calculateTotal(): void
'     + clearCart(): void
' }

' class CartDetail {
'     + id: Int
'     + quantity: Int
'     + price: Double
' }

class Order {
    + id: Int
    + customerPhoneNumber: String
    + totalPrice: Double
    + totalQuantity: Int
    + note: String
    + address: String
    + orderDate: Date
    + orderStatus: Int
    + paymentMethod: Int
    + paymentStatus: Int
    + invoiceNumber: String
    + invoiceDate: Date

    + placeOrder(): void
    + cancelOrder(): void
    + updateStatus(): void
    + generateInvoice(): void
}

class OrderDetail {
    + id: Int
    + priceAtOrder: Double
    + quantity: Int
    + quantity: Int
}

'--- Import ---
class Supplier {
    + id: Int
    + displayName: String
    + address: String
    + email: String
    + phoneNumber: String
    + image: String
    + isActive: Boolean
}

class Shipment {
    + id: Int
    + receiptDate: Date
    + totalPrice: Double
    + totalQuantity: int
    + note: String
}

class Goods {
    + id: Int
    + quantity: Int
    + importPrice: Double
    + totalPrice: Double
}

class Category {
    + id: Int
    + parentId: Int
    + name: String
    + image: String
    + slug: String
    + isActive: Boolean
}

'--------------------Connection--------------------

Product "0..*" o-up-- "1" Category : belongs to
' Product "0..*" -down- "1..*" Cart : contains
' (Cart, Product) . CartDetail : consists of
Product "1..*" -down- "0..*" Order : includes
(Product, Order) .. OrderDetail : contains
Product "1..*" -left-- "0..*" Shipment : part of
(Shipment, Product) . Goods : consists of

Shipment "1..*" -up-- "1" Supplier : supplied by
Shipment "1..*" -up-- "1" Manager : managed by

' Cart "1" -down-- "1" Customer : owned by
' Cart "1" -right- "1" Order : checkout

Order "0..*" -down-- "1" Customer : has
Order "0..*" -left-- "1" SaleStaff : created by

Category "1..*" -right-- "1" Manager : managed by

Customer --|> User
SaleStaff --|> User
Manager --|> User

@enduml
