@startuml SinooUC

skinparam shadowing false
left to right direction

actor "Khách Hàng" as KH
actor "Nhân Viên Quản Lý" as NVQL
actor "Nhân Viên Bán Hàng" as NVBH

rectangle "Hệ thống quản lý bán hàng và kho vật liệu xây dựng Thiên Ân" {

'>>>>>>>>>>>>>>> Khai báo >>>>>>>>>>>>>>>
'Danh mục sp
Usecase QLDMSP as "Quản lý danh mục"

note bottom of QLDMSP: Thêm/Sửa/Xóa danh mục
(Xem danh mục) as XEM_DMSP
(Tìm danh mục) as TIM_DMSP

'Kho hàng
Usecase QLKHO as "Quản lý kho"
note bottom of QLKHO : Xem, tìm kiếm, tạo, cập nhật,  \nhủy phiếu nhập kho và phiếu xuất kho,  \nxem và cập nhật số lượng tồn kho 

(Xem số lượng tồn kho) as XEM_HANG

'Nhân viên
Usecase QLNV as "Quản lý nhân viên"
note bottom of QLNV: Thêm/Sửa/Xóa/Xem/Tìm nhân viên

'Nhà cung cấp
Usecase QLNCC as "Quản lý nhà cung cấp"
note bottom of QLNCC: Thêm/Sửa/Xóa/Xem/Tìm nhà cung cấp
' (Tìm nhà cung cấp) as TIM_NCC

'Báo cáo
(Quản lý báo cáo) as QLBC
note bottom of QLBC: Xem doanh thu, phí nhập, phí xuất hàng

'Khách hàng
(Quản lý KH) as QLKH
note top of QLKH: Thêm/Sửa/Xem/Tìm khách hàng

'Đơn hàng
Usecase QLDH as "Quản lý đơn hàng"
note top of QLDH: Xem, tìm kiếm, thêm, sửa và hủy đơn hàng,  \nxác nhận, theo dõi và cập nhật trạng thái đơn hàng.
' (Tìm đơn) as TIM_DH
' (Xem đơn) as XEM_DH

'Sản phẩm
Usecase QLSP as "Quản lý sản phẩm"
note bottom of QLSP: Thêm/Sửa/Xóa sản phẩm
(Xem sản phẩm) as XEM_SP
(Tìm sản phẩm) as TIM_SP
XEM_SP <.. TIM_SP: extend

'Mua hàng
Usecase QLGH as "Quản lý giỏ hàng"
note top of QLGH: thêm sản phẩm vào giỏ hàng,  \ncập nhật số lượng hoặc xóa sản phẩm khỏi giỏ hàng,  \nđặt hàng, xem lịch sử mua hàng,  \ntheo dõi đơn hàng, yêu cầu hủy đơn hàng,  \nxác nhận hoặc cập nhật thông tin liên hệ và địa chỉ giao hàng.

' (Theo dõi đơn hàng) as THEO_DOI_HANG
' (Xem lịch sử mua hàng) as XEM_LSMH

'Đăng nhập, đăng xuất
(Đăng xuất) as Logout
(Đăng nhập) as Login
(Đăng kí) as SignUp
 Login  .>  Logout: include

'>>>>>>>>>>>>>>> Gán đối tượng >>>>>>>>>>>>>>
'----------- Nhân Viên Quản lý -----------
NVQL --> QLSP
NVQL ----> QLDMSP
NVQL --> QLKHO
NVQL --> QLNV
NVQL --> QLNCC
NVQL --> QLBC
NVQL --> QLKH 
NVQL --> QLDH 

'Tài khoản
NVQL --> Login

'Sản phẩm
QLSP <.. XEM_SP: extend
' QLSP <.. TIM_SP: extend

'Danh mục sp
QLDMSP <.. XEM_DMSP: extend
' QLDMSP <.. XEM_DMSP: extend
' TIM_DMSP <.. XEM_DMSP: extend
XEM_DMSP <.. TIM_DMSP: extend

'Kho hàng
QLKHO <... XEM_HANG: extend

'Nhân viên

'Nhà cung cấp
' QLNCC <.. TIM_NCC: extend

'Báo cáo

'Khách hàng

'Đơn hàng


'----------- Nhân Viên Bán Hàng -----------
QLDH <- NVBH
QLKH <-- NVBH

'Tài khoản
Login <-- NVBH

'Kho
XEM_HANG <--- NVBH

'Danh mục
TIM_DMSP <-- NVBH

'Đơn hàng
' TIM_DH ..> QLDH: extend
' XEM_DH ..> QLDH: extend

'Khách hàng
' XEM_LSMH ..> QLKH: extend

'Sản phẩm
TIM_SP <-- NVBH

'----------- Khách Hàng -----------
QLGH <-- KH

'Tài khoản
SignUp <- KH
Login <-- KH

'Mua hàng
' THEO_DOI_HANG .> QLGH: extend
' XEM_LSMH ..> QLGH: extend

'Sản phẩm
TIM_SP <---- KH

}

@enduml
