@startuml ArietyUC

skinparam shadowing false
left to right direction

actor "Khách Hàng" as KH
actor "Quản Lý/Chủ" as NVQL
actor "Nhân Viên Bán Hàng" as NVBH

rectangle "Hệ thống quản lý bán hàng và kho vật liệu xây dựng Thiên Ân" {

'--------------------------------------Chức năng--------------------------------------
'QL tài khoản
usecase QLTK as "Quản ký tài khoản"
note bottom of QLTK: thêm, sửa, xóa thông tin cá nhân
(Đăng nhập) as DNhap
(Đăng xuất) as DXuat
(Đăng kí) as DKi
(Đổi mật khẩu) as DMKhau

'QL sản phẩm
usecase QLSP as "Quản lý sản phẩm"
note bottom of QLSP: thêm, sửa, xóa sản phẩm
(Xem sản phẩm) as XemSP
(Tìm sản phẩm) as TimSP

'QL danh mục sản phẩm
usecase QLDMSP as "Quản lý danh mục sản phẩm"
note bottom of QLDMSP: thêm, sửa, xóa danh mục
(Xem danh mục) as XemDMSP
(Tìm danh mục) as TimDMSP

'QL nhân viên
usecase QLNV as "Quản lý nhân viên"
note bottom of QLNV: thêm, sửa, xóa, tìm kiếm \nxem thông tin nhân viên

'QL nhà cung cấp
usecase QLNCC as "Quản lý nhà cung cấp"
note bottom of QLNCC: thêm, sửa, xóa nhà cung cấp
(Tìm nhà cung cấp) as TimNCC

'QL đơn hàng
usecase QLDH as "Quản lý đơn hàng"
note bottom of QLDH: xem, tìm kiếm, thêm, sửa đơn hàng \nhủy, xác nhận đơn hàng và \ncập nhật trạng thái đơn hàng
(Theo dõi đơn hàng) as TheoDoiDH

'QL giỏ hàng
usecase QLGH as "Quản lý giỏ hàng"
note bottom of QLGH: thêm, cập nhật số lượng, đặt hàng, xem lịch sử mua hàng, \ntheo dõi, yêu cầu hủy đơn hàng, \nxác nhận hoặc cập nhật thông tin liên hệ, địa chỉ giao hàng

'QL phiếu nhập kho
usecase QLPNKho as "Quản lý phiếu nhập kho"
note bottom of QLPNKho: xem, tìm kiếm, tạo, cập nhật, hủy phiếu nhập kho, \ncập nhật số lượng tồn kho dựa trên đơn hàng và phiếu nhập

'QL khách hàng
usecase QLKH as "Quản lý khách hàng"


'QL báo cáo
usecase QLBC as "Quản lý báo cáo"
(Xem báo cáo) as XemBC

'----------------------------------------------------
'Quản lý/ Chủ

NVQL -> DNhap
NVQL -> DXuat

NVQL --> QLTK
NVQL --> QLSP
NVQL --> QLDMSP
NVQL --> QLNV
NVQL --> QLNCC
NVQL --> QLDH
NVQL --> QLKH
NVQL --> QLPNKho
NVQL --> QLBC

'Nhân viên bán hàng
DNhap <-- NVBH
DXuat <-- NVBH

QLTK <-- NVBH
QLDMSP <-- NVBH
QLDH <-- NVBH

'Khách hàng
DKi <--KH
DNhap <-- KH
DXuat <-- KH

QLTK <-- KH
QLGH <-- KH


}

@enduml
