/'======================
    Bắt đầu version 1
======================='/

@startuml

skinparam shadowing false
skinparam defaultFontName Montserrat
skinparam defaultFontSize 20
skinparam ArrowThickness 2
skinparam ArrowMessageAlignment center
skinparam ArrowHeadColor #FF677D


skinparam note {
    BackgroundColor #FFDDC1
    BorderColor #FFABAB
    FontName Montserrat
    TextAlign center
}
skinparam usecase {
    BackgroundColor #FFABAB
    BorderColor #FFC3A0
    ArrowColor #FF677D
    FontName Montserrat
    BorderThickness 5
}
skinparam actor {
    BorderColor #FFABAB
    BorderThickness 3
}

skinparam rectangle {
    FontName "Montserrat BLack"
    BorderColor #FFC3A0
    BorderThickness 5
    ArrowColor #FF677D
}

left to right direction

'------------- Actor -------------

actor "Nhân viên" as NV
actor "Quản Lý/Chủ" as NVQL
actor "Nhân Viên Bán Hàng" as NVBH
actor "Guest" as GUEST
actor "Khách Hàng" as KH

    '----------- Kế thừa -----------

    ' NVQL --|> NV
    NV <|-left- NVQL
    ' NVBH --|> NV
    NV <|-down- NVBH
    ' KH --|> GUEST
    GUEST <|-right- KH

'------------- Boundary -------------

rectangle "Hệ thống quản lý bán hàng và kho vật liệu xây dựng Thiên Ân" {

    '>>>>>>>>>>>>>>> Khai báo >>>>>>>>>>>>>>>

    '------------- UceeCase Tổng quát -------------

    'Quản lý Tài khoản
    (QL tài khoản) as QLTK
    'Quản lý Danh mục
    (QL danh mục) as QLDM
    'Quản lý Kho hàng
    (QL phiếu nhập kho) as QLKHO
    'Quản lý Nhân viên
    (QL nhân viên) as QLNV
    'Quản lý Nhà cung cấp
    (QL nhà cung cấp) as QLNCC
    'Quản lý Đơn hàng
    (QL đơn hàng) as QLDH
    'Quản lý Sản phẩm
    (QL sản phẩm) as QLSP
    'Quản lý Giỏ hàng
    (QL giỏ hàng) as QLGH
    'Quản lý Khách hàng
    (QL khách hàng) as QLKH

    note bottom of QLTK: Xem, Sửa
    note top of QLDM: Thêm, Sửa, Xóa, Xem, Tìm
    note bottom of QLKHO: Xem, Tìm, Thêm, Sửa, Hủy
    note bottom of QLNCC: Thêm, Sửa, Xóa, Xem
    note bottom of QLDH: Xem, Tìm, Thêm, Sửa, Hủy, Xác nhận
    note top of QLSP: Thêm, Sửa, Xóa
    note bottom of QLGH: Xem, Cập nhật giỏ hàng \nĐặt hàng \nXem lịch sử mua hàng
    note bottom of QLKH: Thêm, Sửa, Xem, Tìm

    '------------- UceeCase Chi tiết -------------

    (Xem danh mục) as XEM_DMSP
    (Xem số lượng tồn kho) as XEM_HANG
    (Tìm đơn) as TIM_DH
    (Xem đơn) as XEM_DH
    (Theo dõi đơn hàng) as THEO_DOI_DH
    (Yêu cầu hủy đơn hàng) as YCHUY_DH
    (Xem sản phẩm) as XEM_SP
    (Tìm sản phẩm) as TIM_SP
    
    (Đăng xuất) as Logout
    (Đăng nhập) as Login
    (Đăng kí) as SignUp
    (Đổi mật khẩu) as ChangePass

    '>>>>>>>>>>>>>>> Hướng >>>>>>>>>>>>>>

    Login <. Logout: include
    ChangePass .> Login : extend
    
    'Tất cả các usecase đều include Login
    QLDM ..> Login : include
    QLDH ..> Login : include
    QLSP ..> Login : include
    QLNCC ..> Login : include
    QLKH ..> Login : include
    QLNV ..> Login : include
    QLKHO ..> Login : include
    Login <.. QLGH: include

    '----------- Nhân viên (Parent) -----------
    
    NV --> QLDH
    NV --> QLTK
    NV --> QLKH

    '----------- Quản lý -----------

    NVQL --> QLDM
    NVQL --> QLKHO
    NVQL --> QLNV
    NVQL --> QLNCC
    NVQL --> QLSP

    'Sản phẩm
    QLSP <... TIM_SP: extend

    'Danh mục sp
    QLDM <.. XEM_DMSP: extend

    'Kho hàng
    QLKHO <.. XEM_HANG  : extend

    'Đơn hàng
    QLDH <.. TIM_DH: extend

    '----------- Nhân Viên Bán Hàng -----------

    ' NVBH ---> XEM_HANG
    ' NVBH --> XEM_DMSP

    XEM_HANG <--- NVBH
    XEM_DMSP <--- NVBH

    '----------- Khách Hàng -----------

    SignUp <- GUEST
    TIM_SP <-- GUEST
    XEM_DMSP <-- GUEST

    XEM_SP <... TIM_SP: extend
    XEM_DH <.. TIM_DH: extend

    QLDH <.. YCHUY_DH: extend
    QLDH <.. THEO_DOI_DH: extend

    QLGH <-- KH
    QLTK <- KH
    YCHUY_DH <-- KH
    THEO_DOI_DH <-- KH
    TIM_DH <-- KH
}

@enduml

/'======================
    Hết vversion 1
======================='/












/'======================
    Bắt đầu version 2
======================='/

@startuml

skinparam shadowing false
left to right direction

'------------- Actor -------------

actor "Nhân viên" as NV
actor "Quản Lý/Chủ" as NVQL
actor "Nhân Viên Bán Hàng" as NVBH
actor "Guest" as GUEST
actor "Khách Hàng" as KH

    '----------- Kế thừa -----------

    ' NVQL --|> NV
    NV <|-- NVQL
    ' NVBH --|> NV
    NV <|-- NVBH
    ' KH --|> GUEST
    GUEST <|-- KH

'------------- Boundary -------------

rectangle "Hệ thống quản lý bán hàng và kho vật liệu xây dựng Thiên Ân" {

    '>>>>>>>>>>>>>>> Khai báo >>>>>>>>>>>>>>>

    '------------- UceeCase Tổng quát -------------

    'Quản lý Tài khoản
    Usecase QLTK as "Quản lý tài khoản
    --
    Xem, Sửa"

    'Quản lý Danh mục
    Usecase QLDM as "Quản lý danh mục
    --
    Thêm, Sửa, Xóa, Xem, Tìm"

    'Quản lý Kho hàng
    Usecase QLKHO as "Quản lý phiếu nhập kho
    --
    Xem, Tìm, Thêm, Sửa, Hủy phiếu nhập kho"

    'Quản lý Nhân viên
    Usecase QLNV as "Quản lý nhân viên
    --
    Thêm, Sửa, Xóa, Xem"

    'Quản lý Nhà cung cấp
    Usecase QLNCC as "Quản lý nhà cung cấp
    --
    Thêm, Sửa, Xóa, Xem"

    'Quản lý Đơn hàng
    Usecase QLDH as "Quản lý đơn hàng
    --
    Xem, Tìm, Thêm, Sửa, Hủy, Xác nhận"

    'Quản lý Sản phẩm
    Usecase QLSP as "Quản lý sản phẩm
    --
    Thêm, Sửa, Xóa"

    'Quản lý Giỏ hàng
    Usecase QLGH as "Quản lý giỏ hàng
    --
    Xem, Cập nhật giỏ hàng / Đặt hàng \nXem lịch sử mua hàng"

    'Quản lý Khách hàng
    Usecase QLKH as "Quản lý khách hàng
    --
    Thêm, Sửa, Xem, Tìm"

    '------------- UceeCase Chi tiết -------------

    (Xem danh mục) as XEM_DMSP
    (Xem số lượng tồn kho) as XEM_HANG
    (Tìm đơn) as TIM_DH
    (Xem đơn) as XEM_DH
    (Theo dõi đơn hàng) as THEO_DOI_DH
    (Yêu cầu hủy đơn hàng) as YCHUY_DH
    (Xem sản phẩm) as XEM_SP
    (Tìm sản phẩm) as TIM_SP
    
    (Đăng xuất) as Logout
    (Đăng nhập) as Login
    (Đăng kí) as SignUp
    (Đổi mật khẩu) as ChangePass

    '>>>>>>>>>>>>>>> Hướng >>>>>>>>>>>>>>

    Login <. Logout: include
    ChangePass .> Login : extend
    
    'Tất cả các usecase đều include Login
    QLDM ..> Login : include
    QLDH ..> Login : include
    QLSP ..> Login : include
    QLNCC ..> Login : include
    QLKH ..> Login : include
    QLNV ..> Login : include
    QLKHO ..> Login : include
    Login <.. QLGH: include

    '----------- Nhân viên (Parent) -----------
    
    NV --> QLDH
    NV --> QLTK
    NV --> QLKH

    '----------- Quản lý -----------

    NVQL --> QLDM
    NVQL --> QLKHO
    NVQL --> QLNV
    NVQL --> QLNCC
    NVQL --> QLSP

    'Sản phẩm
    QLSP <... TIM_SP: extend

    'Danh mục sp
    QLDM <.. XEM_DMSP: extend

    'Kho hàng
    QLKHO <.. XEM_HANG  : extend

    'Đơn hàng
    QLDH <.. TIM_DH: extend

    '----------- Nhân Viên Bán Hàng -----------

    ' NVBH ---> XEM_HANG
    ' NVBH --> XEM_DMSP

    XEM_HANG <--- NVBH
    XEM_DMSP <--- NVBH

    '----------- Khách Hàng -----------

    SignUp <- GUEST
    TIM_SP <-- GUEST
    XEM_DMSP <-- GUEST

    XEM_SP <... TIM_SP: extend
    XEM_DH <.. TIM_DH: extend

    QLDH <.. YCHUY_DH: extend
    QLDH <.. THEO_DOI_DH: extend

    QLGH <-- KH
    QLTK <- KH
    YCHUY_DH <-- KH
    THEO_DOI_DH <-- KH
    TIM_DH <-- KH
}

@enduml

