@startuml SequenceLogin
actor "Quản lý/ NVBH/ KH" as actor
boundary "UI: Đăng nhập" as ui_login
control "Ctrl: Đăng nhập" as ctrl_login
entity "User" as user
database database

activate ui_login
    actor -> ui_login: Nhập tên và tài khoản
    actor -> ui_login: Bấm nút "Đăng nhập"
deactivate ui_login

activate ctrl_login
    ui_login -> ctrl_login: Gửi tên tài khoản và mật khẩu
    ctrl_login -> ctrl_login: Kiểm tra hợp lệ và tồn tại
deactivate ctrl_login


alt #Pink tài khoản và mật khẩu hợp lệ
    ctrl_login -> user: Gửi tên tài khoản, mật khẩu
    activate user
    user -> user: Kiểm tra tồn tại
    deactivate user

alt #LightBlue  tài khoản và mật khẩu tồn tại
    user -> ctrl_login : Thông báo tồn tại
    activate ctrl_login
    activate database
    ctrl_login -> database: Hiển thị giao diện
    deactivate database

else #Yellow
    user -> ctrl_login: Thông báo không tồn tại
    deactivate ctrl_login
    activate ui_login
    ctrl_login -> ui_login: Thông báo: Nhập lại tên/mật khẩu tài khoản

end
    else tài khoản hoặc mật khẩu không hợp lệ
    ctrl_login -> ui_login: Thông báo: Nhập lại tên/mật khẩu tài khoản
    deactivate ui_login
end
deactivate actor

@enduml
