@startuml classdemo

left to right direction

skinparam class {
    BackgroundColor LightPink
    FontColor Black
    FontStyle bold
}

class User {
    + id: string
    + full_name: string
    + phone_number: string
    + address: string
    + gender: string
    + dateOfBirth: string
    + password: string
    'Method
    + ChangePassword(): void
    + ForgotPassword(): void
}

class Managerment {
    + citizen_id: string
    'Method
    + ChangeInfo(): void
    
}

class SaleStaff {
    + citizen_id: string
    + dateOfIssue: date
    + placeOfIssue: string
    'Method
    + PlaceOrderForCustomer(): void
}

class Customer {
    'Method
    + ChangeInfo(): void
    + ViewOrderHistory(): void
}


class Product {
    + id: string
    + name: string
    + price: double
    + unit: string
    + material: string
    + dimensions: string
    + standard: string
    + color: string
    + style: string
    + brand: string
    + warrantyPeriod : string
    + description: string
    + image: list<string>
    + active: bool
    'Method
}

class Cart {
    + id: string
    + totalPrice: double
    + totalQuantity: double
    'Method
    + AddItem(): void
    + RemoveItem(): void
    + CalculateTotal(): void
    + ClearCart(): void
}

class CartItem {
    + id: string
    + quantity: int
    + price: double
}

class Order {
    + id: string
    + customerPhoneNumber: string
    + totalPrice: double
    + orderDate: datetime
    + orderStatus: int
    + paymentStatus: string
    + paymentMethod: string

    'Method
    + PlaceOrder(): void
    + CancelOrder(): void
    + UpdateStatus(): void
}

class OrderItem {
    + id: string
    + price: double
    + quantity: int
    'Method
}

class Invoice {
    + id: string
    + invoiceDate: date
    + totalPrice: double
    + PaymentStatus: string
    + PaymentMethod: string
}


class Supplier {
    + email: string
    + image: string
    + active: bool
    'Method

}

class GoodsReceived {
    + id: string
    + receiptDate: date
    + totalPrice: double
    + note: string
    'Method
}

class GoodsReceivedItem {
    + id: string
    + quantity: int
    + importPrice: double
    + totalPrice: double
}

class Category {
    + id: string
    + parentID: int
    + name: string
    + roomType: string
    + usageType : string
    + description: string
    + active: bool
}



Product "1..*" -up-- "1" Category: belongs to
Product "1..*" -down- "1..*" Cart: added to
' sp duoc them vao gh
(Cart, Product) . CartItem
Product "1..*" -down-- "1..*" Order: includes
' sp nam trong dh
(Product, Order) .. OrderItem
Product "1..*" -left-- "1..*" GoodsReceived: includes
(GoodsReceived, Product) . GoodsReceivedItem


GoodsReceived "1..*" -up-- "1" Supplier: is from
' pnh den tu ncc
GoodsReceived "0..*" -up-- "1" Managerment: manage


Cart "1" -down-- "1" Customer: has
Cart "1" -right-> "1" Order : changes to
' gh thay doi thanh dh. khi kh thanh toan


Order "0..*" -left-- "1" Customer: has
Order "1..*" -right-- "1" SaleStaff: creates
Order "1" -up-- "0..1" Invoice: has


Category "1..*" -right-- "1" Managerment: manage


Customer --|> User
SaleStaff --|> User
Managerment --|> User

@enduml
